### PR TITLE
Upgrade module to SS4

### PR DESCRIPTION
**Pull request by MasseyIsaako**

### CODE REVIEW

**Comment by wilr** [comment]
@Copperis can we get this merged and a new release?

**Comment by h7io** [comment]
I can do that, but I am really no longer working with Silverstripe, so I cannot properly maintain this plugin. @wilr I can transfer the ownership of this repository to you. Are you willing to take it?

**Comment by wilr** [comment]
Yep! Happy to maintain as 2 of our sites use it - can you transfer to @fullscreeninteractive?

Or happy if you just want to add me a collab to this to keep the composer path etc the same.

**Comment by h7io** [comment]
@wilr I need permission to create repositories on @fullscreeninteractive to be able to transfer. 
I am leaning more on the transfer. Git requests should be redirected with the transfer too, so maybe it will work out well.

So do you want me to transfer it to your account or will you grant me temporary permissions on that organisation?

**Comment by wilr** [comment]
@Copperis I think it's also because I have a fork of it setup so you may need to merge this, I'll delete the fork and then you can transfer it.

**Comment by h7io** [comment]
imagen

Ok, though I got this message when attempting the transfer to the organisation.

**Comment by h7io** [comment]
The transfer has completed and the redirects seem to be in effect.
I removed myself from the organisation.
Good luck @wilr and thanks for taking this!

**Pull request merged**
